pyconau/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls


urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', 'search.views.search', name='search'),

    url(r'', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.views.generic import TemplateView

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from wagtail.wagtailadmin.edit_handlers import FieldPanel
from wagtail.wagtailcore.models import Page
from wagtail.wagtailcore.fields import RichTextField


class ContentPage(Page):
    body = RichTextField()

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]

    subpage_types = ['ContentPage']

home/models.py
from __future__ import unicode_literals

from django.db import models

from wagtail.wagtailcore.models import Page
from wagtail.wagtailadmin.edit_handlers import (
    FieldPanel, MultiFieldPanel, PageChooserPanel)

from wagtail.wagtailimages.edit_handlers import ImageChooserPanel

from sponsors.models import Sponsor
from news.models import NewsItem


class HomePage(Page):

    big_text = models.TextField()
    banner_image = models.ForeignKey(
        'wagtailimages.Image', related_name='+',
        on_delete=models.SET_NULL, null=True, blank=False)

    registrations_open = models.BooleanField()
    registrations_link = models.ForeignKey(
        Page, on_delete=models.SET_NULL, null=True, blank=False, related_name='+')

    sponsor_link = models.ForeignKey(
        Page, on_delete=models.SET_NULL, null=True, blank=False, related_name='+')

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('big_text'),
            ImageChooserPanel('banner_image'),
        ], 'Banner'),
        MultiFieldPanel([
            FieldPanel('registrations_open'),
            PageChooserPanel('registrations_link'),
        ], 'Registrations'),
        PageChooserPanel('sponsor_link'),
    ]

    parent_page_types = []

    def get_context(self, request):
        context = super().get_context(request)
        context.update({
            'sponsors': Sponsor.objects.all().order_by('level', 'name'),
            'newsitems': NewsItem.objects.all()[:5],
        })
        return context

news/models.py
from django.db import models
from wagtail.wagtailadmin.edit_handlers import FieldPanel
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailcore.models import Page
from wagtailnews.models import AbstractNewsItem, NewsIndexMixin
from wagtailnews.decorators import newsindex


@newsindex
class NewsIndex(NewsIndexMixin, Page):
    newsitem_model = 'NewsItem'


class NewsItem(AbstractNewsItem):
    title = models.CharField(max_length=255)
    body = RichTextField()

    panels = AbstractNewsItem.panels + [
        FieldPanel('title'),
        FieldPanel('body'),
    ]

    def __str__(self):
        return self.title

schedule/models.py
from django.db import models
from wagtail.wagtailsnippets.models import register_snippet


@register_snippet
class Event(models.Model):
    name = models.CharField(max_length=20)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.name

sponsors/models.py
from django.db import models
from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailcore.models import Page
from wagtail.wagtailadmin.edit_handlers import FieldPanel, PageChooserPanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel


@register_snippet
class Sponsor(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField()
    image = models.ForeignKey(
        'wagtailimages.Image', related_name='+',
        on_delete=models.SET_NULL, null=True, blank=False)
    description = RichTextField()

    LEVEL_CHOICES = [
        ('1-platinum', 'Platinum'),
        ('2-gold', 'Gold'),
        ('3-standard', 'Standard'),
        ('4-contributor', 'Contributor'),
        ('5-in-kind', 'In-kind'),
        ('6-coffee', 'Coffee charity'),
    ]
    level = models.CharField(choices=LEVEL_CHOICES, max_length=20)

    panels = [
        FieldPanel('name'),
        FieldPanel('url'),
        ImageChooserPanel('image'),
        FieldPanel('description'),
        FieldPanel('level'),
    ]

    def __str__(self):
        return self.name


class SponsorPage(Page):
    body = RichTextField()

    content_panels = Page.content_panels + [
        FieldPanel('body'),
    ]

    subpage_types = []

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        context.update({
            'sponsors': Sponsor.objects.all().order_by('level', 'name'),
        })
        return context

search/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from wagtail.wagtailcore.models import Page
from wagtail.wagtailsearch.models import Query, EditorsPick


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()

        # Get search picks
        search_picks = query.editors_picks.all()
    else:
        search_results = Page.objects.none()
        search_picks = EditorsPick.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
        'search_picks': search_picks,
    })

content/templates/content/content_page.html
{% extends "internal_page.html" %}

{% load wagtailcore_tags %}

{% block internal_content %}
    {{ self.body|richtext }}
{% endblock %}

home/templates/home/home_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags pyconau_tags %}

{% block content %}

<div class="banner">
    <div class="container">
        <div class="cta">
            <div class="padding">
                <h1>{{ self.big_text }}</h1>
                {% conf_dates %}
                <a href="/person/new" class="button large">Create Account</a>
                <a href="/person/signin" class="button large grey">Login</a>
            </div>
        </div>
    </div>

    <span data-picture data-alt="Banner Image" class="banner-bg">
        {% image self.banner_image width-768 as small_banner %}
        {% image self.banner_image width-900 as medium_banner %}
        {% image self.banner_image width-1170 as large_banner %}
        {% image self.banner_image original as huge_banner %}

        <span data-src="{{ small_banner.url }}" data-media="(min-width: 401px)"></span>
        <span data-src="{{ medium_banner.url }}" data-media="(min-width: 769px)"></span>
        <span data-src="{{ large_banner.url }}" data-media="(min-width: 901px)"></span>
        <span data-src="{{ huge_banner.url }}" data-media="(min-width: 1171px)"></span>

        <noscript>
            <img src="{{ huge_banner.url }}" alt="PyCon AU 2014">
        </noscript>
    </span>
</div>

{% if self.registrations_open %}
    <div class="important-news">
        <div class="container">
            <h2>Registrations are now open!</h2>
            <a href="{{ self.registrations_link.url }}" class="button">Find out More</a>
        </div>
    </div>
{% endif %}

<div class="container">
    <!-- Sponsors -->
    <h2 class="home-h2">Sponsors</h2>

    <div id="sponsors" class="owl-carousel">
        <div class="item">
            {% for sponsor in sponsors %}
                <div class="item">
                    <a href="{{ sponsor.url }}">
                        {% image sponsor.image fill-268x134 class="scale-with-grid" %}
                        <span>{{ sponsor.get_level_display }}</span>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="content-cta centered">
        <a href="{{ self.sponsor_link.url }}" class="button large">Sponsor PyCon Australia</a>
    </div>

    <!-- News-->
    <h2 class="home-h2">News</h2>

    <div class="nine columns">
        {% for newsitem in newsitems %}
            <article class="homepage-news">
            <p class="date">{{ newsitem.date|date:"d F Y" }}</p>
            <div class="article-body">
            {{ newsitem.body|richtext }}
            </div>
            <div class="clearfix"></div>
            </article>
        {% endfor %}
    </div>

    <div class="three columns">
        <ul class="stay-in-touch fa-ul">
<li><i class="fa-li fa fa-rss"></i> <a href="/media/news/rss">RSS News Feed</a></li>
<li><i class="fa-li fa fa-envelope"></i> <a href="http://lists.linux.org.au/listinfo/pycon-au-announce">Announcements Mailing List</a></li>
<li><i class="fa-li fa fa-twitter"></i> <a href="http://twitter.com/pyconau">@pyconau Twitter</a></li>
<li><i class="fa-li fa fa-comments"></i> <a href="irc://irc.freenode.net/pyconau"><tt>irc.freenode.net/#pyconau</tt></a></li>
<li><i class="fa-li fa fa-google-plus"></i> <a href="http://plus.google.com/+PyConAU">Google+</a></li>
<li><i class="fa-li fa fa-facebook"></i> <a href="http://www.facebook.com/PyConAustralia">Facebook</a></li>
</ul>
    </div>
    <div class="clearfix"></div>

    <!-- Location -->
    <h2 class="home-h2">Location</h2>

    <div class="six columns">
        <div id="map-canvas"></div>
    </div>

    <div class="three columns pullman-images">
        <span data-picture data-alt="Pullman Hotel" class="pullman-img">
            <span data-src="http://2015.pycon-au.org/img/8784_ho_02_p_1024x768.jpg" data-media="(min-width: 1171px)"></span>
        </span>
        <span data-picture data-alt="Pullman Hotel" class="pullman-img">
            <span data-src="http://2015.pycon-au.org/img/8784_sm_00_p_1024x768.jpg" data-media="(min-width: 1171px)"></span>
        </span>
    </div>

    <div class="three columns about-pullman">
        <div class="padding">
            <p class="pullman-address">
                <span>Pullman Hotel</span><br/>
                King George Square<br/>
                Brisbane QLD 4000
            </p>
            <p>The <a href="http://www.pullmanbrisbanekgs.com.au/">Pullman Hotel</a> is located in the Brisbane CBD, 
            just across from the Brisbane City Hall which contain the 
            <a href="http://www.museumofbrisbane.com.au/">Musuem of Brisbane</a>. </p>
            The Pullman is a combined hotel and conference facility, the largest of its type in Brisbane. 
            The Pullman is right next to the retail precinct and public transport.
        </div>
    </div>

    <div class="clearfix"></div>
</div>

{% endblock %}

news/templates/news/news_index.html
{% extends "internal_page.html" %}

{% load wagtailcore_tags wagtailroutablepage_tags %}

{% block internal_content %}
<h1>PyCon Australia 2015 News</h1>

{% for newsitem in newsitem_list %}
    <h2><a href="{{ newsitem.url }}">{{ newsitem.title }}</a></h2>
    <p class="submitted">Submitted on {{ newsitem.date|date:"Y-m-d H:i" }}</p>
    {{ newsitem.body|richtext }}
    <hr>
{% endfor %}

{% endblock %}

news/templates/news/newsitem.html
{% extends "internal_page.html" %}

{% load wagtailcore_tags %}

{% block internal_content %}
<h1>{{ newsitem.title }}</h1>
<p class="submitted">Submitted on {{ newsitem.date|date:"Y-m-d H:i" }}</p>
{{ newsitem.body|richtext }}
{% endblock %}

pyconau/templates/base.html
<!DOCTYPE html>
{% load static wagtailuserbar pyconau_tags %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="prefetch" href="https://login.persona.org/include.js">
        <title>
            {% block title %}{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}{% endblock %}
            {% block title_suffix %} - PyCon Australia | July 31st - August 4th 2015 | Brisbane, Queensland{% endblock %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href='//fonts.googleapis.com/css?family=Oswald:400,700|Oxygen:400,700' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="http://2015.pycon-au.org/css/stylesheets/vendor/font-awesome.css">
        <link rel="stylesheet" href="http://2015.pycon-au.org/css/stylesheets/vendor/owl.carousel.css">
        <link rel="stylesheet" href="http://2015.pycon-au.org/css/stylesheets/vendor/owl.theme.css">

        <link rel="stylesheet" href="http://2015.pycon-au.org/css/stylesheets/style.css">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}

         <!--[if lte IE 9]>
         <link href="http://2015.pycon-au.org/css/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
        <![endif]-->

        <script src="http://2015.pycon-au.org/js/vendor/modernizr-2.6.2.min.js"></script>

    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}

        <div id="flash"></div>


        <header>
            <div class="nav-bg"></div>
            <div class="container">
                <a href="http://2015.pycon-au.org">
                    <!-- PictureFill Responsive Logo -->
                    <span data-picture data-alt="PyCon AU 2015 Logo">
                    <span data-src="http://2015.pycon-au.org/img/mobile-logo.png" class="mobile-logo"></span>
                    <span data-src="http://2015.pycon-au.org/img/logo.png" data-media="(min-width: 769px)" class="logo"></span>

                        <noscript>
                        <img src="http://2015.pycon-au.org/img/logo.png" alt="PyCon AU 2015 Logo" class="logo">
                        </noscript>
                    </span>
                </a>

                <ul class="nav">
                    {% top_menu self %}
                </ul>

                <div class="clearfix"></div>

                <div class="ctas pull-right">
                    <a class="first button block" href="/person/new">Create Account</a>
                    <a class="button grey block" href="/person/signin">Login</a>
                </div>

                <div class="dates pull-right">
                    <h2>31<sup>st</sup> JULY - 4<sup>th</sup> AUGUST 2015</h2>
                    <p class="location">Pullman Brisbane - King George Square</p>
                </div>

                <div class="clearfix"></div>
            </div>
        </header>

        {% block content %}{% endblock %}

        <footer>
            <div class="container">
                <ul class="footer-links">
                    <li><a href="/about/pycon-au">About PyCon Australia</a></li>
                    <li><a href="/register/prices">Prices</a></li>
                    <li><a href="/register/accommodation">Accommodation</a></li>
                    <li><a href="/about/venue">Venue</a></li>
                    <li><a href="/about/history">History</a></li>
                    <li><a href="/register/code_of_conduct">Code of Conduct</a></li>
                </ul>

                <ul class="footer-links">
                    <li><a href="/programme/about">About the Programme</a></li>
                    <li><a href="/programme/keynotes">Keynotes</a></li>
                    <li><a href="/programme/miniconfs">MiniConfs</a></li>
                    <li><a href="/programme/schedule/saturday">Schedule</a></li>
                    <li><a href="/programme/social_events">Social Events</a></li>
                </ul>

                <ul class="footer-links">
                    <li><a href="/sponsors/sponsors">Our Sponsors</a></li>
                    <li><a href="/sponsors/why_sponsor">Why Sponsor</a></li>
                    <li><a href="/media/news">Media</a></li>
                    <li><a href="/media/in_the_press">In the Press</a></li>
                    <li><a href="/media/graphics">Graphics</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>

                {% conf_dates class_name="footer-conf-dates" %}

                <a href="http://2015.pycon-au.org"><img src="http://2015.pycon-au.org/img/white-logo.png" alt="PyConAu Logo" class="pull-right white-logo" /></a>
                <div class="clearfix"></div>
            </div>
        </footer>
        <div class="bottom-footer">
            <div class="container">
                <span>© 2015 <a href="http://pycon-au.org/">PyCon Australia</a> and <a href="http://linux.org.au/">Linux Australia</a></span>
                <span>Designed by <a href="http://kabucreative.com.au">Kabu Creative</a></span>
                <span class="cc-credit pull-right">
                    <span>
                        Banner image by <a href="https://secure.flickr.com/photos/richard_jones/6102827522/sizes/l/">Richard Jones</a> (<a href="https://creativecommons.org/licenses/by/2.0/">CC Attribution</a>)
                    </span>
                </span>
            </div>
            <div class="dark-bottom-footer"></div>
            <div class="bottom-footer-bg"></div>
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="http://2015.pycon-au.orgjs/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="http://2015.pycon-au.orghttps://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>

        <script type="text/javascript">
           jQuery(document).ready(function() {
             jQuery("#flash > div").hide().fadeIn(3500);
             jQuery("#flash > div").fadeTo(3000, 0.3);
             jQuery("#flash > div").hover(function() {
               jQuery(this).fadeTo(250, 1);
             },function(){
               jQuery(this).fadeTo(250, 0.3);
             });
           });
        </script>

        <script src="http://2015.pycon-au.org/js/vendor/owl.carousel.min.js"></script>
        <script src="http://2015.pycon-au.org/js/vendor/picturefill.js"></script>
        <script src="http://2015.pycon-au.org/js/pycon-main.js"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}

        <!-- TODO: Add Google Analytics -->

    </body>
</html>

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/pyconau.css' %}">

    </head>


    </body>
</html>

pyconau/templates/internal_page.html
{% extends "base.html" %}

{% load pyconau_tags %}

{% block content %}

<div class="internal-banner">
    <div class="container">
        <div class="cta offset-by-three">
            <a href="/person/new" class="button large register">Create Account</a>
            {% conf_dates %}
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<div class="container">
    <div class="three columns">

        <div class="sidebar-module">
            <nav class="sidebar-menu">
                {% side_menu self %}
            </nav>
        </div>

        <div class="sidebar-module loop">
            <h3 class="sidebar-title">Stay in the loop</h3>
            <ul class="stay-in-touch fa-ul">
                <li><i class="fa-li fa fa-rss"></i> <a href="/media/news/rss">RSS News Feed</a></li>
                <li><i class="fa-li fa fa-envelope"></i> <a href="http://lists.linux.org.au/listinfo/pycon-au-announce">Announcements Mailing List</a></li>
                <li><i class="fa-li fa fa-twitter"></i> <a href="http://twitter.com/pyconau">@pyconau Twitter</a></li>
                <li><i class="fa-li fa fa-comments"></i> <a href="irc://irc.freenode.net/pyconau"><tt>irc.freenode.net/#pyconau</tt></a></li>
                <li><i class="fa-li fa fa-google-plus"></i> <a href="http://plus.google.com/+PyConAU">Google+</a></li>
                <li><i class="fa-li fa fa-facebook"></i> <a href="http://www.facebook.com/PyConAustralia">Facebook</a></li>
            </ul>
        </div>

        <div class="sidebar-module news">
            <h3 class="sidebar-title">Latest News</h3>
            <div class="news-titles">
                <ul>
                    <li><a href="/media/news/39">Teacher assistance program</a><br />24 July 2015</li>
                    <li><a href="/media/news/38">Keynote Speaker: Carrie Anne Philbin</a><br />13 July 2015</li>
                    <li><a href="/media/news/37">Keynote: Carina C. Zona</a><br />28 June 2015</li>
                    <li><a href="/media/news/36">Programme Released</a><br />24 June 2015</li>
                </ul>
                <a href="/media/news">More News...</a>
            </div>
        </div>
    </div>

    <div class="seven columns">
        <div class="internal-content">
        {% block internal_content %}
        {% endblock %}
        </div>
    </div>

    <div class="two columns">

       <div class="sidebar-logos">
            {% side_sponsors %}
        </div>
    </div>

    <div class="clearfix"></div>
</div>
{% endblock %}

pyconau/templates/tags/conf_dates.html
<ul class="{{ class_name }}">
    {% for event in schedule %}
        <li><strong>{{ event.name }}</strong><br/>
        {% if event.start_date == event.end_date %}
            {{ event.start_date|date:"M j"  }}
        {% elif event.start_date.month == event.end_date.month %}
            {{ event.start_date|date:"M j" }}-{{ event.end_date|date:"j" }}
        {% else %}
            {{ event.start_date|date:"M j" }}-{{ event.end_date|date:"M j" }}
        {% endif %}
    {% endfor %}
</ul>

pyconau/templates/tags/side_menu.html
{% for child in children %}
    <a href="{{ child.url }}" {% if current_page.url == child.url %}class="active"{% endif %}>{{ child.title }} <i class="fa fa-chevron-right pull-right"></i></a>
{% endfor %}

pyconau/templates/tags/side_sponsors.html
{% load wagtailimages_tags %}

{% for sponsor in sponsors %}
    <a href="{{ sponsor.url }}">
        {% image sponsor.image width-177 class="scale-with-grid" %}
    </a>
{% endfor %}

pyconau/templates/tags/top_menu.html
<li class="{% if current_page.url == '/' %}active{% endif %}"><a href="/">Home</a></li>
{% for child in root_page.get_children %}
<li class="{% if current_page.url == child.url %}active{% endif %}"><a href="{{ child.url }}">{{ child.title }}</a></li>
{% endfor %}

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1>Search</h1>

    <form action="{% url 'search' %}" method="get">
        <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
        <input type="submit" value="Search">
    </form>

    {% if search_picks %}
         <ul>
            {% for pick in search_picks %}
                <li>
                    <h2><a href="{{ pick.page.url }}">{{ pick.page }}</a></h2>
                    <p>{{ pick.description }}</p>
                </li>
             {% endfor %}
         </ul>
    {% endif %}

    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
                    {% if result.search_description %}
                        {{ result.search_description|safe }}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        {% if search_results.has_previous %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
        {% endif %}

        {% if search_results.has_next %}
            <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
        {% endif %}
    {% elif search_query %}
        No results found
    {% endif %}
{% endblock %}

sponsors/templates/sponsors/sponsor_page.html
{% extends "internal_page.html" %}

{% load wagtailcore_tags %}

{% block internal_content %}
    {{ self.body|richtext }}

    {% regroup sponsors by get_level_display as level_sponsors %}
    {% for group in level_sponsors %}
        <h2>{{ group.grouper }}</h2>
        {% for sponsor in group.list %}
            <h3><a href="{{ sponsor.url }}">{{ sponsor.name }}</a></h3>
            {{ sponsor.description|richtext }}
        {% endfor %}
        <hr>
    {% endfor %}
{% endblock %}